In [1]:
import numpy as np

Написать функцию get_nonzero_diag_product(X), которая подсчитывает произведение ненулевых элементов на диагонали прямоугольной матрицы. Если все элементы на диагонали нулевые, функция должна вернуть None.


In [2]:
def get_nonzero_diag_product(X):
    diag = np.diag(X)
    if(not np.any(diag != 0)):
        return None
    return np.multiply.reduce(diag[diag != 0])

In [3]:
get_nonzero_diag_product([[0,2],[0,0]])

Написать функцию replace_nan_to_means(X), принимающую матрицу X. Функция должна вернуть копию матрицы X, в которой все значения nan в каждом столбце заменены на среднее арифметическое остальных элементов столбца. В случае столбца из одних nan необходимо заменить все элементы столбца на нули. Исходная матрица X должна остаться неизменной!

In [4]:
def replace_nan_to_means(X):
    Y = X.copy()
    mean = np.nanmean(Y, axis=0)
    mask = np.isnan(Y)
    Y = np.nan_to_num(Y, 0) + mask * np.nan_to_num(mean, 0)[np.newaxis, :]
    return Y


Написать функцию get_max_before_zero(x), возвращающую максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. Если подходящих элементов нет, функция должна возвращать None.

In [5]:
def get_max_before_zero(X):
    mask = X == 0
    if(np.any(mask)):
        mask = np.concatenate((np.array([False]), mask), axis=0)
        ans = X[mask[: -1]]
        if ans.size != 0:
            return ans.max()
    return None


In [6]:
get_max_before_zero(np.array([1,1,0,1]))


1

Написать функцию encode_rle(x), реализующую кодирование длин серий (Run-length encoding). По входному вектору x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй — сколько раз их нужно повторить.

In [7]:
def encode_rle(X):
    bias = np.append(X[1:], X[-1])
    mask = (bias != X)
    mask[-1] = True 
    tmp = np.where(mask)[0]
    tmp[1:] -= tmp[:-1]
    tmp[0] += 1
    return X[mask],tmp


In [8]:
encode_rle(np.array([0,0]))

(array([0]), array([2]))

In [9]:
arr = np.arange(12).reshape(2,-1)
x = np.ones(3)
np.apply_along_axis(np.convolve,1,arr,x)

array([[ 0.,  1.,  3.,  6.,  9., 12.,  9.,  5.],
       [ 6., 13., 21., 24., 27., 30., 21., 11.]])

Охотники за сокровищами отправились за очередным кладом в необычное место, которое называется "Поле чудес". "Поле чудес" имеет размер H на W метров. На каждом квадратном метре "Поля чудес" закопан сундук с определённым количеством камней. Скоро "Поле чудес" должен посетить лепрекон. Под влиянием лепрекона камни в сундуках превращаются в золотые монеты. Лепрекон появляется в определённой клетке поля и действует на прямоугольную область размером h на w, верхний левый край этой области - точка, где стоит лепрекон. Охотники за сокровищами не знают, когда точно появятся лепрекон, но хотят получить как можно больше золота. Известно вероятностное распределение на появление лепрекона в каждый момент времени в каждой клетке поля. Необходимо для каждой клетки "Поля чудес" посчитать математическое ожидание награды, которое будет получено от этой клетки. Необходимо написать функцию calc_expectations(h, w, X, Q), где: h, w - размеры области влияния лепрекона X - размера H на W, матрица целых чисел, X[i, j] - количество камней в i, j клетке Q - размера H на W, двумерная матрица вещественных чисел, вероятностное распределение. Q[i, j] - вероятность появления лепрекона в точке i, j.

In [10]:
X = np.array([ [1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4] ])
Q = np.array([ [0.2, 0, 0.3, 0.1], [0.1, 0, 0.2, 0], [0.05, 0, 0, 0], [0, 0, 0, 0.05]])
def calc_expectations(h,w,X,Q):
    E = np.apply_along_axis(np.convolve, 1, Q,np.ones(w))[:, :Q.shape[1]]
    E = np.apply_along_axis(np.convolve, 0, E, np.ones(h))[:E.shape[0], :]
    E = E * X
    return E


In [11]:
calc_expectations(2,2,X,Q)

array([[0.2 , 0.2 , 0.3 , 0.4 ],
       [0.6 , 0.6 , 1.  , 1.2 ],
       [0.45, 0.45, 0.6 , 0.6 ],
       [0.2 , 0.2 , 0.  , 0.2 ]])